In [1]:
import os
import pandas as pd

In [2]:
directorys = os.listdir("/home/aevans/nwp_bias/data/oksm")

In [8]:
df = pd.read_parquet(
    "/home/aevans/ai2es/processed_data/frcst_err/gfs_fcast_and_error_df_12z_2018_mask_water_ok.parquet"
)
df = df[["t2m_GFS", "t2m_error", "t2m_oksm"]]

In [9]:
df

                                                   t2m_GFS  t2m_error  \
station valid_time          time
ACME    2018-01-01 15:00:00 2018-01-01 12:00:00 -12.881002   0.452331
        2018-01-01 18:00:00 2018-01-01 12:00:00  -7.993199   0.340134
        2018-01-01 21:00:00 2018-01-01 12:00:00  -5.255367   0.855744
        2018-01-02 00:00:00 2018-01-01 12:00:00  -7.773940   0.559393
        2018-01-02 03:00:00 2018-01-01 12:00:00  -8.581052   1.418948
...                                                    ...        ...
YUKO    2018-12-31 18:00:00 2018-12-31 12:00:00   9.111452   2.444785
        2018-12-31 21:00:00 2018-12-28 12:00:00   8.435913  -1.564087
                            2018-12-29 12:00:00  10.434740   0.434740
                            2018-12-30 12:00:00  10.527146   0.527146
                            2018-12-31 12:00:00  10.816411   0.816411

                                                  t2m_oksm
station valid_time          time
ACME    2018-01-01 15:00:00 2018-01-01 12:00:00 -13.333333
        2018-01-01 18:00:00 2018-01-01 12:00:00  -8.333333
        2018-01-01 21:00:00 2018-01-01 12:00:00  -6.111111
        2018-01-02 00:00:00 2018-01-01 12:00:00  -8.333333
        2018-01-02 03:00:00 2018-01-01 12:00:00 -10.000000
...                                                    ...
YUKO    2018-12-31 18:00:00 2018-12-31 12:00:00   6.666667
        2018-12-31 21:00:00 2018-12-28 12:00:00  10.000000
                            2018-12-29 12:00:00  10.000000
                            2018-12-30 12:00:00  10.000000
                            2018-12-31 12:00:00  10.000000

[1337129 rows x 3 columns]

In [5]:
directorys

['oksm_1H_obs_2019.csv',
 'oksm_1H_obs_2021.csv',
 'oksm_3H_obs_2021.csv',
 'oksm_3H_obs_2020.parquet',
 'oksm_3H_obs_2018.parquet',
 'oksm_3H_obs_2020.csv',
 'oksm_1H_obs_2020.parquet',
 'oksm_1H_obs_2021.parquet',
 'oksm_3H_obs_2018.csv',
 'oksm_1H_obs_2018.parquet',
 'oksm_3H_obs_2021.parquet',
 'oksm_3H_obs_2019.parquet',
 'oksm_1H_obs_2019.parquet',
 'oksm_1H_obs_2020.csv',
 'oksm_3H_obs_2019.csv',
 'oksm_1H_obs_2018.csv']

In [6]:
# dfa = pd.read_csv('/home/aevans/nwp_bias/data/oksm/oksm_1H_obs_2019.csv')
# dfb = pd.read_csv('/home/aevans/nwp_bias/data/oksm/oksm_1H_obs_2020.csv')
# dfc = pd.read_csv('/home/aevans/nwp_bias/data/oksm/oksm_1H_obs_2021.csv')
dfd = pd.read_parquet("/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2019.parquet")
# dfe = pd.read_csv('/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2019.csv')
# dff = pd.read_csv('/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2020.csv')
# dfg = pd.read_csv('/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2021.csv')
dfd

                                  lat       lon   elev       tair         td  \
station time_3H
ACME    2019-01-01 06:00:00  34.80833 -98.02325  397.0  -1.666667  24.344607
        2019-01-01 09:00:00  34.80833 -98.02325  397.0  -2.777778  22.627116
        2019-01-01 12:00:00  34.80833 -98.02325  397.0  -3.888889  20.900509
        2019-01-01 15:00:00  34.80833 -98.02325  397.0  -5.000000  19.165006
        2019-01-01 18:00:00  34.80833 -98.02325  397.0  -4.444444  19.930757
...                               ...       ...    ...        ...        ...
YUKO    2019-12-31 09:00:00  35.55671 -97.75538  407.0  -3.333333  22.285175
        2019-12-31 12:00:00  35.55671 -97.75538  407.0  -4.444444  21.324223
        2019-12-31 15:00:00  35.55671 -97.75538  407.0  -0.555556  26.497909
        2019-12-31 18:00:00  35.55671 -97.75538  407.0   8.333333  24.008617
        2019-12-31 21:00:00  35.55671 -97.75538  407.0  10.555556  25.477608

                             relh   SRAD   pres       mslp  wspd_sonic  \
station time_3H
ACME    2019-01-01 06:00:00  76.0    0.0  28.79  27.731201        22.0
        2019-01-01 09:00:00  77.0    0.0  28.84  27.788018        19.0
        2019-01-01 12:00:00  78.0    0.0  28.89  27.844980        17.0
        2019-01-01 15:00:00  79.0   53.0  28.96  27.921499        18.0
        2019-01-01 18:00:00  78.0  120.0  28.98  27.936586        15.0
...                           ...    ...    ...        ...         ...
YUKO    2019-12-31 09:00:00  80.0    0.0  28.77  27.690821         2.0
        2019-12-31 12:00:00  85.0    0.0  28.77  27.699517         5.0
        2019-12-31 15:00:00  77.0  163.0  28.80  27.698645         4.0
        2019-12-31 18:00:00  28.0  556.0  28.78  27.615876         9.0
        2019-12-31 21:00:00  25.0  394.0  28.68  27.504459        12.0

                             wmax_sonic  wdir_sonic  precip_total
station time_3H
ACME    2019-01-01 06:00:00        32.0       348.0           0.0
        2019-01-01 09:00:00        26.0         9.0           0.0
        2019-01-01 12:00:00        24.0         1.0           0.0
        2019-01-01 15:00:00        22.0        20.0           0.0
        2019-01-01 18:00:00        20.0         5.0           0.0
...                                 ...         ...           ...
YUKO    2019-12-31 09:00:00         3.0       236.0           0.0
        2019-12-31 12:00:00         5.0       242.0           0.0
        2019-12-31 15:00:00         5.0       217.0           0.0
        2019-12-31 18:00:00        12.0       299.0           0.0
        2019-12-31 21:00:00        16.0       218.0           0.0

[334287 rows x 13 columns]

In [7]:
dfa.to_parquet("/home/aevans/nwp_bias/data/oksm/oksm_1H_obs_2019.parquet")
dfb.to_parquet("/home/aevans/nwp_bias/data/oksm/oksm_1H_obs_2020.parquet")
dfc.to_parquet("/home/aevans/nwp_bias/data/oksm/oksm_1H_obs_2021.parquet")
dfd.to_parquet("/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2018.parquet")
dfe.to_parquet("/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2019.parquet")
dff.to_parquet("/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2020.parquet")
dfg.to_parquet("/home/aevans/nwp_bias/data/oksm/oksm_3H_obs_2021.parquet")

NameError: name 'dfa' is not defined

In [ ]:
dire

In [ ]:
os.path.exists(
    "/home/aevans/ai2es/GFS/cleanedGFS/2018/11/20181101_gfs.t12z_fhAll.parquet"
)

In [ ]:
df = pd.read_parquet("/home/aevans/nwp_bias/data/nysm/nysm_1H_obs_2021.parquet")

In [ ]:
%%time
df[500000:].dropna()

In [ ]:
df1 = pd.read_csv("/home/aevans/nwp_bias/data/oksm/oksm_1H_obs_2018.csv")
df1.reset_index()

In [ ]:
df1.head()

In [ ]:
df2 = pd.read_parquet(
    "/home/aevans/ai2es/processed_data/GFS/ok/GFS_00z_01-2018_interp_to_oksm_sites_mask_water.parquet"
)
df2

In [ ]:
df3 = pd.read_parquet(
    "/home/aevans/ai2es/processed_data/HRRR/ok/HRRR_00z_01-2018_interp_to_oksm_sites_mask_water.parquet"
)
df3

In [ ]:
df4 = pd.read_parquet(
    "/home/aevans/ai2es/processed_data/frcst_err/hrrr_fcast_and_error_df_12z_2018_mask_water_ny.parquet"
)
df4

In [ ]:
err = pd.read_parquet(
    "/home/aevans/ai2es/processed_data/frcst_err/gfs_fcast_and_error_df_12z_2018_mask_water_ny.parquet"
)
err.keys()

In [ ]:
err

In [ ]:
err_resamp = err[
    [
        "t2m_error",
        "d2m_error",
        "u_total_error",
        "u_dir_error",
        "new_tp_error",
        "prmsl_error",
        "lead_time_DAY",
        "lead_time_HOUR",
        "lead_time_ONLY_HOURS",
    ]
]

In [ ]:
err_resamp_t1 = err_resamp.where(err_resamp["lead_time_ONLY_HOURS"] == 3.0).dropna()

In [ ]:
err_resamp_t1