In [1]:
import xarray as xr
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
ds = pd.read_parquet(
    "/home/aevans/ai2es/HRRR/cleanedHRRR/2018/01/20180101_hrrr.t00z_wrfsfc_fhAll.parquet"
)

In [3]:
ds

                                               t2m          pt      sh2  \
time       y             x
2018-01-01 -5.910277e+05 -5.623610e+05  265.868561  275.170532  0.00191
                         -5.593566e+05  265.993561  275.170532  0.00189
                         -5.563521e+05  265.993561  275.108032  0.00186
                         -5.533477e+05  265.993561  274.983032  0.00183
                         -5.503432e+05  265.931061  274.858032  0.00180
...                                            ...         ...      ...
            1.383248e+06  2.435715e+06  262.289734  261.494385  0.00099
                          2.438718e+06  262.227234  261.556885  0.00101
                          2.441721e+06  262.352234  261.619385  0.00102
                          2.444724e+06  262.477234  261.681885  0.00102
                          2.447727e+06  262.352234  261.681885  0.00102

                                               d2m         r2       u10  \
time       y             x
2018-01-01 -5.910277e+05 -5.623610e+05  262.545013  77.699997 -3.777693
                         -5.593566e+05  262.420013  76.599998 -3.777693
                         -5.563521e+05  262.232513  75.500000 -3.715193
                         -5.533477e+05  261.982513  74.300003 -3.652693
                         -5.503432e+05  261.795013  73.400002 -3.590193
...                                            ...        ...       ...
            1.383248e+06  2.435715e+06  256.054749  62.700001  2.531862
                          2.438718e+06  256.242249  64.300003  2.719362
                          2.441721e+06  256.367249  64.500000  2.719362
                          2.444724e+06  256.367249  63.900002  2.969362
                          2.447727e+06  256.429749  64.699997  3.969362

                                             v10      si10     asnow     tp  \
time       y             x
2018-01-01 -5.910277e+05 -5.623610e+05 -1.255184  4.163785  0.000068  0.005
                         -5.593566e+05 -1.442684  4.163785  0.000076  0.006
                         -5.563521e+05 -1.567684  4.163785  0.000087  0.007
                         -5.533477e+05 -1.567684  4.226285  0.000088  0.007
                         -5.503432e+05 -1.630184  4.163785  0.000075  0.007
...                                          ...       ...       ...    ...
            1.383248e+06  2.435715e+06  0.982368  2.871020  0.000000  0.000
                          2.438718e+06  0.982368  2.871020  0.000000  0.000
                          2.441721e+06  0.919868  2.996020  0.000000  0.000
                          2.444724e+06  0.857368  3.621020  0.000000  0.000
                          2.447727e+06  1.044868  4.433520  0.000000  0.000

                                           mslma         orog   latitude  \
time       y             x
2018-01-01 -5.910277e+05 -5.623610e+05  102500.0  1242.057739  32.999181
                         -5.593566e+05  102510.0  1231.807739  33.000925
                         -5.563521e+05  102520.0  1224.151489  33.002660
                         -5.533477e+05  102531.0  1213.588989  33.004386
                         -5.503432e+05  102542.0  1205.807739  33.006103
...                                          ...          ...        ...
            1.383248e+06  2.435715e+06  101219.0     7.995255  47.014054
                          2.438718e+06  101218.0    22.370255  47.004860
                          2.441721e+06  101218.0    18.432755  46.995655
                          2.444724e+06  101217.0    14.682755  46.986440
                          2.447727e+06  101216.0    19.526505  46.977215

                                         longitude          valid_time
time       y             x
2018-01-01 -5.910277e+05 -5.623610e+05 -103.498195 2018-01-01 01:00:00
                         -5.593566e+05 -103.466239 2018-01-01 01:00:00
                         -5.563521e+05 -103.434281 2018-01-01 01:00:00
                         -5.533477e+05 -103.402322 2018-01-01 01:00:00
                         -5.503432e+05 -103.370362 2018-01-01 01:00:00
...                                            ...                 ...
            1.383248e+06  2.435715e+06  -65.121879 2018-01-01 18:00:00
                          2.438718e+06  -65.085166 2018-01-01 18:00:00
                          2.441721e+06  -65.048464 2018-01-01 18:00:00
                          2.444724e+06  -65.011773 2018-01-01 18:00:00
                          2.447727e+06  -64.975092 2018-01-01 18:00:00

[11915640 rows x 15 columns]